nodeName: node1
db:
  type: sqlite
  sqlite:
    dsn: ':memory:'
    autoMigrate: true
    migrationsDir: '../../../core/go/db/migrations/sqlite'
rpcServer:
  http:
    port: 0
    shutdownTimeout: 0s
  ws:
    disabled: true
    shutdownTimeout: 0s
grpc:
  shutdownTimeout: 0s
blockIndexer:
  fromBlock: latest
blockchain:
  http:
    url: http://localhost:8545
  ws:
    url: ws://localhost:8546
    initialConnectAttempts: 25
log:
  level: debug
  output: file
  file:
    filename: build/testbed.domain-noto.log
wallets:
- name: wallet1
  keySelector: .*
  signer:
    keyDerivation:
      type: "bip32"
    keyStore:
      type: "static"
      static:
        keys:
          seed:
            encoding: none
            inline: REPLACED BY GENERATED KEY IN TEST