name: "Modify Repository Name"
description: "Outputs a modified repository name based on given inputs."
inputs:
  repository:
    description: "The original repository name."
    required: true
  registry:
    description: "The registry name."
    required: true
outputs:
  repository:
    description: "The modified repository name after applying rules."
    value: ${{ steps.modify_repository.outputs.repository }}
runs:
  using: "composite"
  steps:
    - name: modify_repository
      id: modify_repository
      shell: bash
      run: |
        # Step 1: Convert repository name to lowercase
        repository_lower=$(echo "${{ inputs.repository }}" | tr '[:upper:]' '[:lower:]')
        
        # Initialize the modified repository with the lowercase name
        modified_repository="$repository_lower"
        
        # Step 2: If repository is LFDT-Paladin,
        # replace with lfdecentralizedtrust
        if [ "$repository_lower" = "lfdt-paladin" ]; then
          modified_repository="lfdecentralizedtrust"
        fi
        
        # Set the output
        echo "repository=$modified_repository" >> $GITHUB_OUTPUT