name: 'Update YAML File'
description: 'Update values in a YAML file'
inputs:
  file:
    description: 'The path to the YAML file to update'
    required: true
  updates:
    description: 'YAML content with the updates to apply'
    required: true
  strip_v_prefix:
    description: 'Whether to strip the leading v from tag values (true/false)'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install yq
      shell: bash
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
        chmod +x yq
        sudo mv yq /usr/local/bin/

    - name: Update YAML file
      shell: bash
      run: |
        set -e
        echo "Applying updates to ${{ inputs.file }}"

        # Write the updates to a temporary YAML file
        echo "${{ inputs.updates }}" > updates.yaml

        # Optionally strip 'v' prefix
        if [ "${{ inputs.strip_v_prefix }}" = "true" ]; then
          yq e 'walk(if type == "!!str" then sub("^v"; "") else . end)' -i updates.yaml
        fi

        # Merge the updates into the target YAML file
        yq e -i '. * load("updates.yaml")' "${{ inputs.file }}"

        echo "Updated ${{ inputs.file }}:"
        cat "${{ inputs.file }}"
