name: 'Update YAML File'
description: 'Update values in a YAML file'
inputs:
  file:
    description: 'The path to the YAML file to update'
    required: true
  updates:
    description: 'YAML content with the updates to apply'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install yq
      shell: bash
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
        chmod +x yq
        sudo mv yq /usr/local/bin/

    - name: Update YAML file
      shell: bash
      run: |
        set -e
        echo "Applying updates to ${{ inputs.file }}"

        # Write the updates to a temporary YAML file
        echo "${{ inputs.updates }}" > updates.yaml

        # Merge the updates into the target YAML file
        yq e -i '. * load("updates.yaml")' "${{ inputs.file }}"

        echo "Updated ${{ inputs.file }}:"
        cat "${{ inputs.file }}"
