template: testify
pkgname: "{{.SrcPackageName}}mocks"
structname: "{{.InterfaceName}}"
filename: "{{.SrcPackageName}}mocks.go"
dir: "mocks/{{.SrcPackageName}}mocks"
packages:
  github.com/LFDT-Paladin/paladin/sdk/go/pkg/rpcclient:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/toolkit/pkg/rpcserver:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/toolkit/pkg/signer:
    interfaces:
      SigningModule:
  github.com/LFDT-Paladin/paladin/core/pkg/blockindexer:
    interfaces:
      BlockIndexer:
  github.com/LFDT-Paladin/paladin/core/pkg/ethclient:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/components:
    config:
      all: true
    interfaces:
      KeyManager:
  github.com/LFDT-Paladin/paladin/core/internal/componentmgr:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/metrics:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/privatetxnmgr/ptmgrtypes:
    config:
      all: true
    interfaces:
      TransactionFlow:
        config:
          dir: "{{.InterfaceDir}}"
          filename: "mock_transaction_flow.go"
          pkgname: "{{.SrcPackageName}}"
          structname: "Mock{{.InterfaceName}}"
  github.com/LFDT-Paladin/paladin/core/internal/privatetxnmgr/syncpoints:
    config:
      all: true
  github.com/LFDT-Paladin/paladin/core/internal/publictxmgr:
    interfaces:
      InFlightStageActionTriggers:
