name: Paladin Operator Build

on:
  pull_request:
    paths:
      - 'operator/**'
  workflow_dispatch:

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  operator-build:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: paladin
      NAMESPACE: paladin

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      # - name: Go Lint
      #   working-directory: operator
      #   run: make lint

      # - name: Unit Tests
      #   working-directory: operator
      #   run: make test

      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true # only install kind, the cluster creation is managed by the deploy step
          ignore_failed_clean: true
      
      # The makefile uses kustomize
      - uses: imranismail/setup-kustomize@v2

      - name: Deploy Operator
        run: ./gradlew deploy -PclusterName=${{ env.CLUSTER_NAME }} -Pnamespace=${{ env.NAMESPACE }} 

      - name: Uninstall Operator
        run: ./gradlew clean -PclusterName=${{ env.CLUSTER_NAME }} -Pnamespace=${{ env.NAMESPACE }} -PdeleteCluster=true