name: Paladin Build
permissions:
  contents: write
  packages: write
  id-token: write

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'operator/charts/**'
  pull_request:
  workflow_dispatch:

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

# Start =================================================================================================

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install pre-requisites
        uses: ./.github/actions/setup

      # Build with Gradle
      # This does not build any docker images, and does not run any dockerized tests.
      # It does run Go/Java/Solidity component and integration tests that use PostgreSQL and Besu
      - name: Build with Gradle
        run: ./gradlew -PcomposeLogs=true -PverboseTests=true --no-daemon --parallel --max-workers=5 build

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()      
        with:
          name: testbed-logs
          path: |
            **/testbed.*.log

  core-image-build:
    # run only on PRs
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build-image.yaml
    with:
      dockerfile: ./Dockerfile
      registry: paladin.io
      image: paladin
      image_tag: ${{ github.sha }}
      push: false
      upload-artifact: true
      platforms: linux/amd64
      runs-on: ubuntu-latest
# END =================================================================================================
  operator-image-build:
      # run only on PRs
      if: github.event_name == 'pull_request'
      uses: ./.github/workflows/build-image.yaml
      with:
        dockerfile: ./operator/Dockerfile
        registry: paladin.io
        image: paladin-operator
        image_tag: ${{ github.sha }}
        push: false
        upload-artifact: true
        platforms: linux/amd64
        runs-on: ubuntu-latest

  # chart-build:
  #   # run only if pull_request and the path operator/** was changed
  #   if: github.event_name == 'pull_request'
  #   needs: [operator-image-build]
  #   # needs: [core-image-build, operator-image-build]
  #   uses: ./.github/workflows/build-chart.yaml
  #   with:
  #     paladin-image: dwertent/paladin
  #     paladin-image-tag: latest
  #     operator-image: paladin.io/paladin-operator
  #     operator-image-tag: ${{ github.sha }}

  chart-build:
    # run only if pull_request and the path operator/** was changed
    if: github.event_name == 'pull_request'
    # needs: [operator-image-build]
    needs: [core-image-build, operator-image-build]
    uses: ./.github/workflows/build-chart.yaml
    with:
      paladin-image: paladin.io/paladin
      paladin-image-tag: ${{ github.sha }}
      operator-image: paladin.io/paladin-operator
      operator-image-tag: ${{ github.sha }}

  image-release:
    # run only on pushes to main or manual triggers
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/cross-build-images.yaml
    with:
      registry: ghcr.io
      repository: ${{ github.repository_owner }}
      image_tags: ${{ github.ref_name }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      