name: Helm Chart release

on:
  push:
    branches:
      - helm-release-job # just for testing
  workflow_dispatch:
    inputs:
      latest:
        required: false
        type: boolean
        default: false

jobs:
  helm-chart-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Prepare CRD chart
        working-directory: operator
        run: gradle prepareCRDsChart

      - name: Prepare operator chart
        working-directory: operator
        run: gradle prepareOperatorChart

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: ${{ inputs.latest }}
          charts_dir: "operator/charts"

          skip_existing: true
        env: 
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
