name: CLI SDK Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        description: 'NPM token'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install pre-requisites
        uses: ./.github/actions/setup
       
      - name: Publish to npm
        working-directory: sdk/typescript
        shell: bash
        run: |
          set -e
          ../../gradlew build
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}