name: Helm Chart release

on:
  workflow_dispatch:
    inputs:
      latest:
        required: false
        type: boolean
        default: false
      tag:
        required: true
        type: string
        description: 'The tag to release the chart and images with'
  
jobs:
  helm-chart-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Install protoc only on non-Windows systems
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
          unzip protoc-25.1-linux-x86_64.zip -d protoc
          echo "${PWD}/protoc/bin" >> $GITHUB_PATH

      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache-dependency-path: |
            **/*.sum

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      # The makefile uses kustomize
      - uses: imranismail/setup-kustomize@v2

      - name: Prepare CRD chart
        run: ./gradlew prepareCRDsChart

      - name: Prepare operator chart
        run: ./gradlew prepareOperatorChart
      
      # build and release images
      - name: Build and release images
        uses: ./.github/workflows/release-images.yaml
        with:
          tag: ${{ inputs.tag }}
          latest: ${{ inputs.latest }}

      - name: Set Lowercase Repository Owner
        run: echo "LOWER_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      
      # Override the image tags in the values.yaml file 
      - name: Override image tags
        uses: ./.github/actions/update-yaml
        with:
          file: 'operator/charts/paladin-operator/values.yaml'
          updates: |
            operator:
              image:
                repository: docker.io/${{ env.LOWER_REPOSITORY_OWNER }}/paladin-operator
                tag: ${{ inputs.tag }}
            paladin:
              image:
                repository: docker.io/${{ env.LOWER_REPOSITORY_OWNER }}/paladin
                tag: ${{ inputs.tag }}
        
      # Override the chart version in the Chart.yaml file
      - name: Override chart version
        uses: ./.github/actions/update-yaml
        with:
          file: 'operator/charts/paladin-operator/Chart.yaml'
          strip_v_prefix: 'true'
          updates: |
            version: ${{ inputs.tag }}
            appVersion: ${{ inputs.tag }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: ${{ inputs.latest }}
          charts_dir: "operator/charts"
          skip_existing: true
        env: 
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
